<?php
$phone_codes = [
    ['rus' => 'Абхазия', 'eng' => 'Abkhazia', 'code' => 7],
    ['rus' => 'Австралия', 'eng' => 'Australia', 'code' => 61],
    ['rus' => 'Австрия', 'eng' => 'Austria', 'code' => 43],
    ['rus' => 'Азербайджан', 'eng' => 'Azerbaijan', 'code' => 994],
    ['rus' => 'Албания', 'eng' => 'Albania', 'code' => 355],
    ['rus' => 'Алжир', 'eng' => 'Algeria', 'code' => 213],
    ['rus' => 'Американское Самоа', 'eng' => 'American Samoa', 'code' => 685],
    ['rus' => 'Ангилья', 'eng' => 'Anguilla', 'code' => 1264],
    ['rus' => 'Ангола', 'eng' => 'Angola', 'code' => 244],
    ['rus' => 'Андорра', 'eng' => 'Andorra', 'code' => 376],
    ['rus' => 'Антарктида', 'eng' => 'Antarctica', 'code' => 1],
    ['rus' => 'Антигуа и Барбуда', 'eng' => 'Antigua and Barbuda', 'code' => 1268],
    ['rus' => 'Аргентина', 'eng' => 'Argentina', 'code' => 54],
    ['rus' => 'Армения', 'eng' => 'Armenia', 'code' => 374],
    ['rus' => 'Аруба', 'eng' => 'Aruba', 'code' => 297],
    ['rus' => 'Афганистан', 'eng' => 'Afghanistan', 'code' => 93],
    ['rus' => 'Багамы', 'eng' => 'The Bahamas', 'code' => 1242],
    ['rus' => 'Бангладеш', 'eng' => 'Bangladesh', 'code' => 880],
    ['rus' => 'Барбадос', 'eng' => 'Barbados', 'code' => 1246],
    ['rus' => 'Бахрейн', 'eng' => 'Bahrain', 'code' => 973],
    ['rus' => 'Белиз', 'eng' => 'Belize', 'code' => 501],
    ['rus' => 'Белоруссия', 'eng' => 'Belarus', 'code' => 375],
    ['rus' => 'Бельгия', 'eng' => 'Belgium', 'code' => 32],
    ['rus' => 'Бенин', 'eng' => 'Benin', 'code' => 229],
    ['rus' => 'Бермудские острова', 'eng' => 'Bermuda', 'code' => 1441],
    ['rus' => 'Болгария', 'eng' => 'Bulgaria', 'code' => 359],
    ['rus' => 'Боливия', 'eng' => 'Bolivia', 'code' => 591],
    ['rus' => 'Босния и Герцеговина', 'eng' => 'Bosnia and Herzegovina', 'code' => 387],
    ['rus' => 'Ботсвана', 'eng' => 'Botswana', 'code' => 267],
    ['rus' => 'Бразилия', 'eng' => 'Brazil', 'code' => 55],
    ['rus' => 'Британская территория в Индийском океане', 'eng' => 'British Indian Ocean Territory', 'code' => 1],
    ['rus' => 'Британские Виргинские острова', 'eng' => 'British Virgin Islands', 'code' => 1284],
    ['rus' => 'Бруней-Даруссалам', 'eng' => 'Brunei', 'code' => 673],
    ['rus' => 'Буркина-Фасо', 'eng' => 'Burkina Faso', 'code' => 226],
    ['rus' => 'Бурунди', 'eng' => 'Burundi', 'code' => 257],
    ['rus' => 'Бутан', 'eng' => 'Bhutan', 'code' => 975],
    ['rus' => 'Вануату', 'eng' => 'Vanuatu', 'code' => 678],
    ['rus' => 'Ватикан', 'eng' => 'Holy See (Vatican City)', 'code' => 39],
    ['rus' => 'Великобритания', 'eng' => 'United Kingdom', 'code' => 44],
    ['rus' => 'Венгрия', 'eng' => 'Hungary', 'code' => 36],
    ['rus' => 'Венесуэла', 'eng' => 'Venezuela', 'code' => 58],
    ['rus' => 'Виргинские острова США', 'eng' => 'Virgin Islands', 'code' => 1340],
    ['rus' => 'Вьетнам', 'eng' => 'Vietnam', 'code' => 84],
    ['rus' => 'Габон', 'eng' => 'Gabon', 'code' => 241],
    ['rus' => 'Гаити', 'eng' => 'Haiti', 'code' => 509],
    ['rus' => 'Гайана', 'eng' => 'Guyana', 'code' => 592],
    ['rus' => 'Гамбия', 'eng' => 'The Gambia', 'code' => 220],
    ['rus' => 'Гана', 'eng' => 'Ghana', 'code' => 233],
    ['rus' => 'Гваделупа', 'eng' => 'Guadeloupe', 'code' => 590],
    ['rus' => 'Гватемала', 'eng' => 'Guatemala', 'code' => 502],
    ['rus' => 'Гвинея', 'eng' => 'Guinea', 'code' => 224],
    ['rus' => 'Гвинея-Бисау', 'eng' => 'Guinea-Bissau', 'code' => 245],
    ['rus' => 'Германия', 'eng' => 'Germany', 'code' => 49],
    ['rus' => 'Гернси', 'eng' => 'Guernsey', 'code' => 1],
    ['rus' => 'Гибралтар', 'eng' => 'Gibraltar', 'code' => 350],
    ['rus' => 'Гондурас', 'eng' => 'Honduras', 'code' => 504],
    ['rus' => 'Гонконг', 'eng' => 'Hong Kong', 'code' => 852],
    ['rus' => 'Гренада', 'eng' => 'Grenada', 'code' => 1473],
    ['rus' => 'Гренландия', 'eng' => 'Greenland', 'code' => 299],
    ['rus' => 'Греция', 'eng' => 'Greece', 'code' => 30],
    ['rus' => 'Грузия', 'eng' => 'Georgia', 'code' => 995],
    ['rus' => 'Гуам', 'eng' => 'Guam', 'code' => 1671],
    ['rus' => 'Дания', 'eng' => 'Denmark', 'code' => 45],
    ['rus' => 'Демократическая Республика Конго', 'eng' => 'Democratic Republic of the Congo', 'code' => 243],
    ['rus' => 'Джерси', 'eng' => 'Jersey', 'code' => 1],
    ['rus' => 'Джибути', 'eng' => 'Djibouti', 'code' => 253],
    ['rus' => 'Доминика', 'eng' => 'Dominica', 'code' => 1767],
    ['rus' => 'Доминиканская Республика', 'eng' => 'Dominican Republic', 'code' => 1829],
    ['rus' => 'Египет', 'eng' => 'Egypt', 'code' => 20],
    ['rus' => 'Замбия', 'eng' => 'Zambia', 'code' => 260],
    ['rus' => 'Западная Сахара', 'eng' => 'Western Sahara', 'code' => 1],
    ['rus' => 'Зимбабве', 'eng' => 'Zimbabwe', 'code' => 263],
    ['rus' => 'Израиль', 'eng' => 'Israel', 'code' => 972],
    ['rus' => 'Индия', 'eng' => 'India', 'code' => 91],
    ['rus' => 'Индонезия', 'eng' => 'Indonesia', 'code' => 62],
    ['rus' => 'Иордания', 'eng' => 'Jordan', 'code' => 962],
    ['rus' => 'Ирак', 'eng' => 'Iraq', 'code' => 964],
    ['rus' => 'Иран', 'eng' => 'Iran', 'code' => 98],
    ['rus' => 'Ирландия', 'eng' => 'Ireland', 'code' => 353],
    ['rus' => 'Исландия', 'eng' => 'Iceland', 'code' => 354],
    ['rus' => 'Испания', 'eng' => 'Spain', 'code' => 34],
    ['rus' => 'Италия', 'eng' => 'Italy', 'code' => 39],
    ['rus' => 'Йемен', 'eng' => 'Yemen', 'code' => 967],
    ['rus' => 'Кабо-Верде', 'eng' => 'Cape Verde', 'code' => 238],
    ['rus' => 'Казахстан', 'eng' => 'Kazakhstan', 'code' => 7],
    ['rus' => 'Каймановы острова', 'eng' => 'Cayman Islands', 'code' => 1345],
    ['rus' => 'Камбоджа', 'eng' => 'Cambodia', 'code' => 855],
    ['rus' => 'Камерун', 'eng' => 'Cameroon', 'code' => 237],
    ['rus' => 'Канада', 'eng' => 'Canada', 'code' => 1],
    ['rus' => 'Катар', 'eng' => 'Qatar', 'code' => 974],
    ['rus' => 'Кения', 'eng' => 'Kenya', 'code' => 254],
    ['rus' => 'Кипр', 'eng' => 'Cyprus', 'code' => 357],
    ['rus' => 'Кирибати', 'eng' => 'Kiribati', 'code' => 686],
    ['rus' => 'Китай', 'eng' => 'China', 'code' => 86],
    ['rus' => 'Кокосовые острова', 'eng' => 'Cocos (Keeling) Islands', 'code' => 1],
    ['rus' => 'Колумбия', 'eng' => 'Colombia', 'code' => 57],
    ['rus' => 'Коморы', 'eng' => 'Comoros', 'code' => 269],
    ['rus' => 'Конго', 'eng' => 'Republic of the Congo', 'code' => 242],
    ['rus' => 'Косово', 'eng' => 'Kosovo', 'code' => 383],
    ['rus' => 'Коста-Рика', 'eng' => 'Costa Rica', 'code' => 506],
    ['rus' => 'Кот д’Ивуар', 'eng' => 'Cote d’Ivoire', 'code' => 225],
    ['rus' => 'Куба', 'eng' => 'Cuba', 'code' => 53],
    ['rus' => 'Кувейт', 'eng' => 'Kuwait', 'code' => 965],
    ['rus' => 'Лаос', 'eng' => 'Laos', 'code' => 856],
    ['rus' => 'Латвия', 'eng' => 'Latvia', 'code' => 371],
    ['rus' => 'Лесото', 'eng' => 'Lesotho', 'code' => 266],
    ['rus' => 'Либерия', 'eng' => 'Liberia', 'code' => 231],
    ['rus' => 'Ливан', 'eng' => 'Lebanon', 'code' => 961],
    ['rus' => 'Ливия', 'eng' => 'Libya', 'code' => 218],
    ['rus' => 'Литва', 'eng' => 'Lithuania', 'code' => 370],
    ['rus' => 'Лихтенштейн', 'eng' => 'Liechtenstein', 'code' => 423],
    ['rus' => 'Люксембург', 'eng' => 'Luxembourg', 'code' => 352],
    ['rus' => 'Маврикий', 'eng' => 'Mauritius', 'code' => 230],
    ['rus' => 'Мавритания', 'eng' => 'Mauritania', 'code' => 222],
    ['rus' => 'Мадагаскар', 'eng' => 'Madagascar', 'code' => 261],
    ['rus' => 'Майотта', 'eng' => 'Mayotte', 'code' => 1],
    ['rus' => 'Макао', 'eng' => 'Macau', 'code' => 853],
    ['rus' => 'Малави', 'eng' => 'Malawi', 'code' => 265],
    ['rus' => 'Малайзия', 'eng' => 'Malaysia', 'code' => 60],
    ['rus' => 'Мали', 'eng' => 'Mali', 'code' => 223],
    ['rus' => 'Малые Тихоокеанские отдаленные острова США', 'eng' => 'United States Pacific Island Wildlife Refuges', 'code' => 1],
    ['rus' => 'Мальдивы', 'eng' => 'Maldives', 'code' => 960],
    ['rus' => 'Мальта', 'eng' => 'Malta', 'code' => 356],
    ['rus' => 'Марокко', 'eng' => 'Morocco', 'code' => 212],
    ['rus' => 'Мартиника', 'eng' => 'Martinique', 'code' => 596],
    ['rus' => 'Маршалловы острова', 'eng' => 'Marshall Islands', 'code' => 692],
    ['rus' => 'Мексика', 'eng' => 'Mexico', 'code' => 52],
    ['rus' => 'Микронезия', 'eng' => 'Micronesia, Federated States of', 'code' => 691],
    ['rus' => 'Мозамбик', 'eng' => 'Mozambique', 'code' => 258],
    ['rus' => 'Молдавия', 'eng' => 'Moldavia', 'code' => 373],
    ['rus' => 'Монако', 'eng' => 'Monaco', 'code' => 377],
    ['rus' => 'Монголия', 'eng' => 'Mongolia', 'code' => 976],
    ['rus' => 'Монтсеррат', 'eng' => 'Montserrat', 'code' => 1664],
    ['rus' => 'Мьянма', 'eng' => 'Burma', 'code' => 95],
    ['rus' => 'Намибия', 'eng' => 'Namibia', 'code' => 264],
    ['rus' => 'Науру', 'eng' => 'Nauru', 'code' => 674],
    ['rus' => 'Непал', 'eng' => 'Nepal', 'code' => 977],
    ['rus' => 'Нигер', 'eng' => 'Niger', 'code' => 227],
    ['rus' => 'Нигерия', 'eng' => 'Nigeria', 'code' => 234],
    ['rus' => 'Нидерландские Антилы', 'eng' => 'Netherlands Antilles', 'code' => 1],
    ['rus' => 'Никарагуа', 'eng' => 'Nicaragua', 'code' => 505],
    ['rus' => 'Ниуэ', 'eng' => 'Niue', 'code' => 683],
    ['rus' => 'Новая Зеландия', 'eng' => 'New Zealand', 'code' => 64],
    ['rus' => 'Новая Каледония', 'eng' => 'New Caledonia', 'code' => 687],
    ['rus' => 'Норвегия', 'eng' => 'Norway', 'code' => 47],
    ['rus' => 'Объединенные Арабские Эмираты', 'eng' => 'United Arab Emirates', 'code' => 971],
    ['rus' => 'Оман', 'eng' => 'Oman', 'code' => 968],
    ['rus' => 'Остров Буве', 'eng' => 'Bouvet Island', 'code' => 1],
    ['rus' => 'Остров Клиппертон', 'eng' => 'Clipperton Island', 'code' => 1],
    ['rus' => 'Остров Мэн', 'eng' => 'Isle of Man', 'code' => 1],
    ['rus' => 'Остров Норфолк', 'eng' => 'Norfolk Island', 'code' => 672],
    ['rus' => 'Остров Рождества', 'eng' => 'Christmas Island', 'code' => 1],
    ['rus' => 'Остров Святого Мартина', 'eng' => 'Saint Martin', 'code' => 1],
    ['rus' => 'Остров Херд и острова Макдональд', 'eng' => 'Heard Island and McDonald Islands', 'code' => 1],
    ['rus' => 'Острова Кука', 'eng' => 'Cook Islands', 'code' => 682],
    ['rus' => 'Острова Тёркс и Кайкос', 'eng' => 'Turks and Caicos Islands', 'code' => 1649],
    ['rus' => 'Пакистан', 'eng' => 'Pakistan', 'code' => 92],
    ['rus' => 'Палау', 'eng' => 'Palau', 'code' => 680],
    ['rus' => 'Панама', 'eng' => 'Panama', 'code' => 507],
    ['rus' => 'Папуа-Новая Гвинея', 'eng' => 'Papua New Guinea', 'code' => 675],
    ['rus' => 'Парагвай', 'eng' => 'Paraguay', 'code' => 595],
    ['rus' => 'Перу', 'eng' => 'Peru', 'code' => 51],
    ['rus' => 'Питкерн', 'eng' => 'Pitcairn', 'code' => 1],
    ['rus' => 'Польша', 'eng' => 'Poland', 'code' => 48],
    ['rus' => 'Португалия', 'eng' => 'Portugal', 'code' => 351],
    ['rus' => 'Пуэрто-Рико', 'eng' => 'Puerto Rico', 'code' => 1787],
    ['rus' => 'Республика Македония', 'eng' => 'Macedonia', 'code' => 389],
    ['rus' => 'Реюньон', 'eng' => 'Reunion', 'code' => 262],
    ['rus' => 'Россия', 'eng' => 'Russia', 'code' => 7],
    ['rus' => 'Руанда', 'eng' => 'Rwanda', 'code' => 250],
    ['rus' => 'Румыния', 'eng' => 'Romania', 'code' => 40],
    ['rus' => 'Самоа', 'eng' => 'Samoa', 'code' => 685],
    ['rus' => 'Сан-Марино', 'eng' => 'San Marino', 'code' => 378],
    ['rus' => 'Сан-Томе и Принсипи', 'eng' => 'Sao Tome and Principe', 'code' => 239],
    ['rus' => 'Саудовская Аравия', 'eng' => 'Saudi Arabia', 'code' => 966],
    ['rus' => 'Свазиленд', 'eng' => 'Swaziland', 'code' => 268],
    ['rus' => 'Святая Елена', 'eng' => 'Saint Helena', 'code' => 1],
    ['rus' => 'Северная Корея', 'eng' => 'Korea, North', 'code' => 850],
    ['rus' => 'Северные Марианские острова', 'eng' => 'Northern Mariana Islands', 'code' => 1670],
    ['rus' => 'Сейшелы', 'eng' => 'Seychelles', 'code' => 248],
    ['rus' => 'Сен-Бартельми', 'eng' => 'Saint Barthélemy', 'code' => 1],
    ['rus' => 'Сен-Пьер и Микелон', 'eng' => 'Saint Pierre and Miquelon', 'code' => 508],
    ['rus' => 'Сенегал', 'eng' => 'Senegal', 'code' => 221],
    ['rus' => 'Сент-Винсент и Гренадины', 'eng' => 'Saint Vincent and the Grenadines', 'code' => 1784],
    ['rus' => 'Сент-Китс и Невис', 'eng' => 'Saint Kitts and Nevis', 'code' => 1869],
    ['rus' => 'Сент-Люсия', 'eng' => 'Saint Lucia', 'code' => 1758],
    ['rus' => 'Сербия', 'eng' => 'Serbia', 'code' => 381],
    ['rus' => 'Сингапур', 'eng' => 'Singapore', 'code' => 65],
    ['rus' => 'Сирия', 'eng' => 'Syria', 'code' => 963],
    ['rus' => 'Словакия', 'eng' => 'Slovakia', 'code' => 421],
    ['rus' => 'Соломоновы острова', 'eng' => 'Solomon Islands', 'code' => 677],
    ['rus' => 'Сомали', 'eng' => 'Somalia', 'code' => 252],
    ['rus' => 'Судан', 'eng' => 'Sudan', 'code' => 249],
    ['rus' => 'Суринам', 'eng' => 'Suriname', 'code' => 597],
    ['rus' => 'США', 'eng' => 'United States', 'code' => 1],
    ['rus' => 'Сьерра-Леоне', 'eng' => 'Sierra Leone', 'code' => 232],
    ['rus' => 'Таджикистан', 'eng' => 'Tajikistan', 'code' => 992],
    ['rus' => 'Таиланд', 'eng' => 'Thailand', 'code' => 66],
    ['rus' => 'Тайвань', 'eng' => 'Taiwan', 'code' => 886],
    ['rus' => 'Танзания', 'eng' => 'Tanzania', 'code' => 255],
    ['rus' => 'Тимор-Лесте', 'eng' => 'Timor-Leste', 'code' => 670],
    ['rus' => 'Того', 'eng' => 'Togo', 'code' => 228],
    ['rus' => 'Токелау', 'eng' => 'Tokelau', 'code' => 690],
    ['rus' => 'Тонга', 'eng' => 'Tonga', 'code' => 676],
    ['rus' => 'Тринидад и Тобаго', 'eng' => 'Trinidad and Tobago', 'code' => 1868],
    ['rus' => 'Тувалу', 'eng' => 'Tuvalu', 'code' => 688],
    ['rus' => 'Тунис', 'eng' => 'Tunisia', 'code' => 216],
    ['rus' => 'Туркмения', 'eng' => 'Turkmenistan', 'code' => 993],
    ['rus' => 'Турция', 'eng' => 'Turkey', 'code' => 90],
    ['rus' => 'Уганда', 'eng' => 'Uganda', 'code' => 256],
    ['rus' => 'Узбекистан', 'eng' => 'Uzbekistan', 'code' => 998],
    ['rus' => 'Украина', 'eng' => 'Ukraine', 'code' => 380],
    ['rus' => 'Уоллис и Футуна', 'eng' => 'Wallis and Futuna', 'code' => 681],
    ['rus' => 'Уругвай', 'eng' => 'Uruguay', 'code' => 598],
    ['rus' => 'Фарерские острова', 'eng' => 'Faroe Islands', 'code' => 298],
    ['rus' => 'Фиджи', 'eng' => 'Fiji', 'code' => 679],
    ['rus' => 'Филиппины', 'eng' => 'Philippines', 'code' => 63],
    ['rus' => 'Финляндия', 'eng' => 'Finland', 'code' => 358],
    ['rus' => 'Фолклендские острова', 'eng' => 'Falkland Islands (Islas Malvinas)', 'code' => 500],
    ['rus' => 'Франция', 'eng' => 'France', 'code' => 33],
    ['rus' => 'Французская Гвиана', 'eng' => 'French Guiana', 'code' => 594],
    ['rus' => 'Французская Полинезия', 'eng' => 'French Polynesia', 'code' => 689],
    ['rus' => 'Французские Южные территории', 'eng' => 'French Southern Lands', 'code' => 1],
    ['rus' => 'Хорватия', 'eng' => 'Croatia', 'code' => 385],
    ['rus' => 'Центральноафриканская Республика', 'eng' => 'Central African Republic', 'code' => 236],
    ['rus' => 'Чад', 'eng' => 'Chad', 'code' => 235],
    ['rus' => 'Черногория', 'eng' => 'Montenegro', 'code' => 382],
    ['rus' => 'Чехия', 'eng' => 'Czech Rep.', 'code' => 420],
    ['rus' => 'Чили', 'eng' => 'Chile', 'code' => 56],
    ['rus' => 'Швейцария', 'eng' => 'Switzerland', 'code' => 41],
    ['rus' => 'Швеция', 'eng' => 'Sweden', 'code' => 46],
    ['rus' => 'Шпицберген и Ян Майен', 'eng' => 'Svalbard and Jan Mayen', 'code' => 1],
    ['rus' => 'Шри-Ланка', 'eng' => 'Sri Lanka', 'code' => 94],
    ['rus' => 'Эквадор', 'eng' => 'Ecuador', 'code' => 593],
    ['rus' => 'Экваториальная Гвинея', 'eng' => 'Equatorial Guinea', 'code' => 240],
    ['rus' => 'Эландские острова', 'eng' => 'Åland Islands', 'code' => 1],
    ['rus' => 'Эль-Сальвадор', 'eng' => 'El Salvador', 'code' => 503],
    ['rus' => 'Эритрея', 'eng' => 'Eritrea', 'code' => 291],
    ['rus' => 'Эстония', 'eng' => 'Estonia', 'code' => 372],
    ['rus' => 'Эфиопия', 'eng' => 'Ethiopia', 'code' => 251],
    ['rus' => 'Южная Африка', 'eng' => 'South Africa', 'code' => 27],
    ['rus' => 'Южная Джорджия и Южные Сандвичевы острова', 'eng' => 'South Georgia and the South Sandwich Islands', 'code' => 1],
    ['rus' => 'Южная Корея', 'eng' => 'Korea, South', 'code' => 82],
    ['rus' => 'Ямайка', 'eng' => 'Jamaica', 'code' => 1876],
    ['rus' => 'Япония', 'eng' => 'Japan', 'code' => 81],
];